INSERT INTO ARTISTS VALUES (1,  'A R Rehman');
INSERT INTO ARTISTS VALUES (2,  'Arijit Singh');
INSERT INTO ARTISTS VALUES (3,  'Mika Singh');


INSERT INTO ALBUMS VALUES (1, 'Roja', 1990, 1);
INSERT INTO ALBUMS VALUES (2, 'Jai Ho', 2015, 1);
INSERT INTO ALBUMS VALUES (3, 'Aashiqui', 2015, 2);
INSERT INTO ALBUMS VALUES (4, 'Sultan', 2000, 3);


INSERT INTO GENRES VALUES (1, 'Sufi');
INSERT INTO GENRES VALUES (1, 'Old');
INSERT INTO GENRES VALUES (1, 'Romance');
INSERT INTO GENRES VALUES (2, 'Romance');
INSERT INTO GENRES VALUES (3, 'Dance');