INSERT INTO USERS VALUES (1, sysdate(), 'USER A');
INSERT INTO USERS VALUES (2, sysdate(), 'USER B');
INSERT INTO USERS VALUES (3, sysdate(), 'USER C');


INSERT INTO POSTS VALUES (1, 'POST A', 1990, 1);
INSERT INTO POSTS VALUES (2, 'POST AA', 2015, 1);
INSERT INTO POSTS VALUES (3, 'POST AAA', 2015, 1);
INSERT INTO POSTS VALUES (4, 'POST B', 2000, 2);
INSERT INTO POSTS VALUES (5, 'POST BB', 2015, 2);
INSERT INTO POSTS VALUES (6, 'POST C', 2000, 3);
INSERT INTO POSTS VALUES (7, 'POST CC', 2015, 3);


--INSERT INTO COMMENTS VALUES (1, 'COMMENT A A', 1, 1);
--INSERT INTO COMMENTS VALUES (2, 'COMMENT A B', 1, 2);
--INSERT INTO COMMENTS VALUES (3, 'COMMENT B A', 2, 1);
--INSERT INTO COMMENTS VALUES (4, 'COMMENT C A', 3, 1);
--INSERT INTO COMMENTS VALUES (5, 'COMMENT C B', 3, 2);